export { CommunityCoreModule } from './community-core.module';
export type { ById, IdViewer, LikeInput, LikeResult, Owned, OwnedById, Viewer } from './community-core.types';
export { IdParamsDto, LikeResultDto, SlugParamsDto } from './dto/community-core.dto';
export { arenaIdSchema, moderationStatusSchema, playerStatsSchema, postStatusSchema } from './dto/community-core.schemas';
export { readRequirements, unmetRequirements } from './lib/requirements/requirements';
export { statRequirementsSchema } from './lib/requirements/requirements.schemas';
export type { PlayerStats } from './lib/requirements/requirements.types';
export { titleSlug } from './lib/slug/slug';
export { toAuthorView } from './mappers/community-views.mappers';
export type { AuthorUser, NamesById, StatsByAccount } from './mappers/community-views.types';
export { AUTHOR_SELECT } from './selects/author.selects';
export { CommunityAccountsReaderService } from './services/community-accounts-reader.service';
export { CommunityContentWriterService } from './services/community-content-writer.service';
