import type { Prisma } from '../../../../generated';

export const DISPOSABLE_USER_COUNTS = {
  lestaAccounts: true,
  follows: true,
  goals: true,
  pushSubscriptions: true,
  modDevices: true,
  apiKeys: true,
  webhookEndpoints: true,
  subscriptions: true,
  payments: true,
  promoRedemptions: true,
  referralsMade: true,
  streamerIntegrations: true,
  streamerClaims: true,
  streamerFollows: true,
  settingsApplies: true,
  overlays: true,
  challenges: true,
  replays: true,
  builds: true,
  guides: true,
  reactions: true,
  comments: true,
  platoonPosts: true,
  recruitingPosts: true,
  tacticBoards: true,
  coachingOrders: true,
  tournaments: true,
  clanWorkspaces: true,
  recruitCandidates: true,
  bonusCodeReports: true,
  missionProgress: true,
  shellLedger: true,
  seasonProgress: true,
  cosmetics: true,
  contentReports: true,
  competitions: true,
  competitionEntries: true
} as const satisfies Prisma.UserCountOutputTypeSelect;
