export const REPLAYS_RU = {
  title: 'Реплеи',
  search: 'Поиск: карта, танк или имя файла',
  clearSearch: 'Очистить поиск',
  resultAll: 'Все',
  result_win: 'Победы',
  result_loss: 'Поражения',
  result_draw: 'Ничьи',
  filterMap: 'Карта',
  filterVehicle: 'Техника',
  filterNation: 'Нация',
  filterTier: 'Уровень',
  filterType: 'Тип боя',
  filterPeriod: 'Период',
  any: 'Любой',
  anyMap: 'Любая',
  anyVehicle: 'Любая',
  anyNation: 'Любая',
  nation_ussr: 'СССР',
  nation_germany: 'Германия',
  nation_usa: 'США',
  nation_china: 'Китай',
  nation_france: 'Франция',
  nation_uk: 'Великобритания',
  nation_japan: 'Япония',
  nation_czech: 'Чехословакия',
  nation_sweden: 'Швеция',
  nation_poland: 'Польша',
  nation_italy: 'Италия',
  nation_intunion: 'Сборная наций',
  period_all: 'Всё время',
  period_today: 'Сутки',
  period_week: 'Неделя',
  period_month: 'Месяц',
  favourites: 'Избранное',
  sortBy: 'Сортировка',
  sort_time: 'Дата',
  sort_damage: 'Урон',
  sort_assist: 'Помощь',
  sort_xp: 'Опыт',
  sort_kills: 'Фраги',
  sort_duration: 'Длительность',
  sort_size: 'Размер',
  descending: 'По убыванию',
  ascending: 'По возрастанию',
  resetFilters: 'Сбросить фильтры',
  refresh: 'Обновить',
  openFolder: 'Папка',
  siteList: 'Мои реплеи на сайте',
  shown: 'Показано',
  of: 'из',
  winRate: 'Победы',
  avgDamage: 'Ср. урон',
  avgAssist: 'Ср. помощь',
  avgXp: 'Ср. опыт',
  indexing: 'Читаем реплеи',
  type_random: 'Случайный бой',
  type_ranked: 'Ранговый бой',
  type_comp7: 'Натиск',
  type_frontline: 'Линия фронта',
  type_royale: 'Стальной охотник',
  type_training: 'Тренировка',
  type_tournament: 'Турнир',
  type_clan: 'Клановый бой',
  type_team: 'Командный бой',
  type_event: 'Событие',
  type_other: 'Особый бой',
  outcome_win: 'Победа',
  outcome_loss: 'Поражение',
  outcome_draw: 'Ничья',
  outcome_unknown: 'Бой не досмотрен',
  damage: 'Урон',
  assist: 'Помощь',
  kills: 'Фраги',
  assistShort: 'пом.',
  killsShort: 'фр.',
  spotted: 'Обнаружено',
  xp: 'Опыт',
  credits: 'Серебро',
  shots: 'Выстрелы',
  hits: 'Попадания',
  pens: 'Пробития',
  received: 'Получено урона',
  blocked: 'Заблокировано',
  duration: 'Длительность боя',
  lifeTime: 'Время жизни',
  survived: 'Выжил',
  destroyed: 'Уничтожен',
  size: 'МБ',
  version: 'Версия клиента',
  noResults: 'В реплее нет итогов: вы вышли из боя раньше конца, поэтому урона, опыта и серебра в нём нет.',
  watch: 'Смотреть',
  watchConfirm: 'Клиент перезапустится и сразу покажет этот бой. После просмотра нажмите «Закончить» — клиент вернётся к входу в игру. Продолжить?',
  watchVersion: 'Реплей записан в версии {version}, клиент — {client}. Клиент показывает только реплеи своей версии.',
  upload: 'Загрузить на сайт',
  uploadOff: 'Чтобы загружать реплеи, включите «Загрузку реплеев» в разделе данных.',
  uploadUnbound: 'Чтобы загружать реплеи, привяжите мод к сайту.',
  uploadMissing: 'Компонент «Загрузка реплеев» не установлен.',
  uploadNoArena: 'В этом реплее нет номера боя: сайт его не примет.',
  site_queued: 'В очереди',
  site_uploaded: 'На сайте',
  site_analysed: 'Разбор готов',
  openOnSite: 'Открыть на сайте',
  favouriteAdd: 'В избранное',
  favouriteRemove: 'Убрать из избранного',
  rename: 'Переименовать',
  viewHits: 'Посмотреть попадания',
  renameSave: 'Сохранить',
  remove: 'Удалить',
  removeConfirm: 'Удалить реплей ({name}) с диска? Это нельзя отменить.',
  confirm: 'Да',
  cancel: 'Отмена',
  close: 'Закрыть',
  pick: 'Выберите реплей в списке',
  offTitle: 'Менеджер реплеев выключен',
  offHint: 'Включите компонент, чтобы видеть свои реплеи здесь.',
  turnOn: 'Включить',
  noAccount: 'Войдите в игру: список показывает только реплеи вашего аккаунта.',
  empty: 'В папке игры нет реплеев ваших боёв. Включите запись боёв в настройках игры, на вкладке «Игра».',
  nothingFound: 'Под поиск и фильтры ничего не подходит.',
  invalid: 'Не удалось прочитать список реплеев. Обновите его.'
} as const;
