import type { ReplaysStrings } from './strings.types';

export const REPLAYS_EN: ReplaysStrings = {
  title: 'Replays',
  search: 'Search: map, tank or file name',
  clearSearch: 'Clear the search',
  resultAll: 'All',
  result_win: 'Wins',
  result_loss: 'Losses',
  result_draw: 'Draws',
  filterMap: 'Map',
  filterVehicle: 'Vehicle',
  filterNation: 'Nation',
  filterTier: 'Tier',
  filterType: 'Battle type',
  filterPeriod: 'Period',
  any: 'Any',
  anyMap: 'Any',
  anyVehicle: 'Any',
  anyNation: 'Any',
  nation_ussr: 'USSR',
  nation_germany: 'Germany',
  nation_usa: 'USA',
  nation_china: 'China',
  nation_france: 'France',
  nation_uk: 'UK',
  nation_japan: 'Japan',
  nation_czech: 'Czechoslovakia',
  nation_sweden: 'Sweden',
  nation_poland: 'Poland',
  nation_italy: 'Italy',
  nation_intunion: 'Combined Nations',
  period_all: 'All time',
  period_today: 'Day',
  period_week: 'Week',
  period_month: 'Month',
  favourites: 'Favourites',
  sortBy: 'Sort',
  sort_time: 'Date',
  sort_damage: 'Damage',
  sort_assist: 'Assist',
  sort_xp: 'XP',
  sort_kills: 'Frags',
  sort_duration: 'Duration',
  sort_size: 'Size',
  descending: 'Descending',
  ascending: 'Ascending',
  resetFilters: 'Reset filters',
  refresh: 'Refresh',
  openFolder: 'Folder',
  siteList: 'My replays on the site',
  shown: 'Shown',
  of: 'of',
  winRate: 'Wins',
  avgDamage: 'Avg damage',
  avgAssist: 'Avg assist',
  avgXp: 'Avg XP',
  indexing: 'Reading replays',
  type_random: 'Random battle',
  type_ranked: 'Ranked battle',
  type_comp7: 'Onslaught',
  type_frontline: 'Frontline',
  type_royale: 'Steel Hunter',
  type_training: 'Training',
  type_tournament: 'Tournament',
  type_clan: 'Clan battle',
  type_team: 'Team battle',
  type_event: 'Event',
  type_other: 'Special battle',
  outcome_win: 'Victory',
  outcome_loss: 'Defeat',
  outcome_draw: 'Draw',
  outcome_unknown: 'Not watched to the end',
  damage: 'Damage',
  assist: 'Assist',
  kills: 'Frags',
  assistShort: 'ast.',
  killsShort: 'frags',
  spotted: 'Spotted',
  xp: 'XP',
  credits: 'Credits',
  shots: 'Shots',
  hits: 'Hits',
  pens: 'Penetrations',
  received: 'Damage received',
  blocked: 'Blocked',
  duration: 'Battle length',
  lifeTime: 'Time alive',
  survived: 'Survived',
  destroyed: 'Destroyed',
  size: 'MB',
  version: 'Client version',
  noResults: 'The replay has no results: you left the battle before its end, so it has no damage, XP or credits.',
  watch: 'Watch',
  watchConfirm: 'The client restarts and shows this battle at once. When it ends, press Finish and the client returns to the login screen. Go on?',
  watchVersion: 'The replay was recorded in version {version}, the client is {client}. The client only shows replays of its own version.',
  upload: 'Upload to the site',
  uploadOff: 'To upload replays, turn Replay upload on in the data section.',
  uploadUnbound: 'To upload replays, bind the mod to the site.',
  uploadMissing: 'The Replay upload component is not installed.',
  uploadNoArena: 'This replay has no battle id: the site will not accept it.',
  site_queued: 'Queued',
  site_uploaded: 'On the site',
  site_analysed: 'Analysis ready',
  openOnSite: 'Open on the site',
  favouriteAdd: 'Add to favourites',
  favouriteRemove: 'Remove from favourites',
  rename: 'Rename',
  viewHits: 'View hits',
  renameSave: 'Save',
  remove: 'Delete',
  removeConfirm: 'Delete the replay ({name}) from the disk? This cannot be undone.',
  confirm: 'Yes',
  cancel: 'Cancel',
  close: 'Close',
  pick: 'Pick a replay in the list',
  offTitle: 'The replay manager is off',
  offHint: 'Turn the component on to see your replays here.',
  turnOn: 'Turn on',
  noAccount: 'Log in to the game: the list shows only the replays of your account.',
  empty: 'No replays of your battles in the game folder. Turn battle recording on in the game settings, on the Game tab.',
  nothingFound: 'Nothing matches the search and filters.',
  invalid: 'The replay list could not be read. Refresh it.'
};
