export { THRESHOLD_SOURCE_PRIORITY } from './config/thresholds.constants';
export { VEHICLE_STATUS } from './config/vehicle-status.constants';
export { bonusTypesOfMode, gameModeOfBonusType } from './lib/bonus-type/bonus-type';
export { ARENA_BONUS_TYPE, GAME_MODE_BONUS_TYPES } from './lib/bonus-type/bonus-type.constants';
export { bronyaReferencePayload, parseBronyaReference } from './lib/bronya-reference/bronya-reference';
export { BRONYA_REFERENCE } from './lib/bronya-reference/bronya-reference.constants';
export { isPreferentialVehicle, readSpecTraits, toTankRole } from './lib/vehicle-status/vehicle-status';
export type { SpecTraits } from './lib/vehicle-status/vehicle-status.types';
export { masteryThresholdLevels, moeThresholdLevels, toMoeThresholdRecord } from './mappers/threshold-record.mappers';
export { toMasteryThreshold, toMoeThreshold } from './mappers/threshold-view.mappers';
export { readVehicleStats, toVehicleStats } from './mappers/vehicle-stats.mappers';
export type { StoredProfile } from './mappers/vehicle-stats.types';
export { unknownVehicle } from './mappers/vehicle-summary.mappers';
export { ReferenceCoreModule } from './reference-core.module';
export { ReferenceModule } from './reference.module';
export type { CatalogEntry, MasteryLevels, MasteryThresholdRecord, MoeLevels, MoeThresholdRecord, ThresholdSet } from './reference.types';
export { BronyaReferencesReaderService } from './services/bronya-references-reader.service';
export { ExpectedValuesReaderService } from './services/expected-values-reader.service';
export { OfficialRatingTypesReaderService } from './services/official-rating-types-reader.service';
export { ThresholdsReaderService } from './services/thresholds-reader.service';
export { VehicleCatalogService } from './services/vehicle-catalog.service';
