export {
  ARMOR_FLAGS,
  armorFlags,
  armorPieceKind,
  base64ToBytes,
  bytesToBase64,
  decodeArmorGeometry,
  encodeArmorGeometry,
  ERF_APPROXIMATION,
  hasArmorFlag,
  listArmorGuns,
  PENETRATION,
  penetrationAtDistance,
  SHELL_KINDS,
  SHELL_RULES,
  toShellKind,
  traceArmorRay
} from './armor';
export type {
  ArmorChassisModule,
  ArmorFlag,
  ArmorGeometry,
  ArmorGunModule,
  ArmorModules,
  ArmorPieceGeometry,
  ArmorPieceKind,
  ArmorPlate,
  ArmorShell,
  ArmorShellOption,
  ArmorTrace,
  ArmorTraceLayer,
  ArmorTurretModule,
  ArmorVerdict,
  Vec3
} from './armor';
export { calculateLoadout, resolveModules } from './loadout';
export type { FinalStats, InstalledDevice, LoadoutInput, ModulePreset } from './loadout';
export {
  aimCurve,
  aimTimeline,
  ballisticsCurve,
  ballisticsDistances,
  camouflageFactor,
  effectiveViewRange,
  flightTime,
  FOLIAGE_KINDS,
  handlingScore,
  penetrationAt,
  scenarioAims,
  scenarioMotion,
  SPOTTING,
  spottingDuel
} from './math';
export type { FoliageKind, GunHandling, HandlingScenario, SpottingDuel, SpottingVerdict } from './math';
export { CREW_ROLES, NATIONS } from './model';
export type {
  Armor,
  Chassis,
  CrewData,
  CrewMember,
  CrewRole,
  CrewSkill,
  Currency,
  Engine,
  Equipment,
  EquipmentKind,
  FieldModification,
  FuelTank,
  Gun,
  ModificationPair,
  ModuleBase,
  Nation,
  OptionalDevice,
  OptionalDeviceKind,
  PitchLimits,
  PitchPoint,
  PostProgression,
  Price,
  ProgressionFeature,
  ProgressionTree,
  Radio,
  RateOfFire,
  Shell,
  Shot,
  SkillBoost,
  SkillParam,
  Turret,
  Unlock,
  VehicleClass,
  VehicleFilter,
  VehicleFilterRule,
  VehicleListEntry,
  VehicleProgressionStep,
  VehicleSpec
} from './model';
export { MODIFIER_OPS } from './modifiers';
export type { DeviceTagFilter, Modifier, ModifierCondition } from './modifiers';
