export const UI_ICON_NAMES = [
  'logo',
  'swords',
  'warehouse',
  'award',
  'clapperboard',
  'radio',
  'globe',
  'layers',
  'layout-dashboard',
  'search',
  'x',
  'minus',
  'plus',
  'rotate-ccw',
  'undo-2',
  'chevron-down',
  'chevron-up',
  'chevron-right',
  'external-link',
  'link',
  'check',
  'circle-alert',
  'circle-check',
  'triangle-alert',
  'info',
  'move-diagonal-2',
  'zoom-in',
  'zoom-out',
  'monitor',
  'crosshair',
  'gauge',
  'medal',
  'chart-line',
  'star',
  'chart-column',
  'clipboard-list',
  'trophy',
  'badge-check',
  'activity',
  'goal',
  'coffee',
  'scroll-text',
  'zap',
  'target',
  'heart-pulse',
  'lightbulb',
  'timer',
  'package',
  'hourglass',
  'move-horizontal',
  'shield-alert',
  'skull',
  'trees',
  'bomb',
  'users',
  'wrench',
  'map',
  'video',
  'volume-2',
  'message-square-off',
  'eye-off',
  'eraser',
  'sliders-horizontal',
  'shield',
  'list-checks',
  'users-round',
  'refresh-cw',
  'bell-off',
  'film',
  'cloud-upload',
  'puzzle',
  'user',
  'save',
  'pencil',
  'trash',
  'copy',
  'download',
  'keyboard',
  'maximize-2',
  'ellipsis',
  'play',
  'folder',
  'arrow-down',
  'arrow-up',
  'arrow-left'
] as const;

export const UI_ICON_TONES = ['muted', 'text', 'accent', 'contrast', 'success', 'danger', 'gold'] as const;

export const UI_ICONS = {
  file: 'icons.png',
  cell: 40,
  columns: 16,
  viewBox: 24,
  strokeWidth: 2,
  names: UI_ICON_NAMES,
  tones: UI_ICON_TONES,
  toneTokens: {
    muted: 'color-text-muted',
    text: 'color-text',
    accent: 'color-accent',
    contrast: 'color-accent-contrast',
    success: 'color-success',
    danger: 'color-danger',
    gold: 'color-gold'
  }
} as const;
